export default {
  "baseData":[
    {
      "num": 0,
      "iconUrl": "",
      "englishName": "all",
      "chineseName": "全部",
      "description": "上海市生活垃圾分类投放指南。",
      "backgroundColor":"",
      "list": []
    },
    {
      "num": 5,
      "iconUrl": "household.svg",
      "englishName":"household",
      "chineseName": "湿垃圾",
      "description":"即易腐物质，指废食材、剩菜饭、过期食品、瓜皮果核、花卉绿植、中药药渣等易腐烂的生物质废弃物。",
      "backgroundColor":"#FAEDCC",
      "list": [
        {
          "name": "茶叶及中药药渣",
          "englishName": "chayejizhongyaoyaozha",
          "shareImgUrl": "http://i2.tiimg.com/693828/1fe4c667a1bc79da.jpg",
          "imgUrl": "../../images/household/chaye.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物","植物"],
          "solution": "茶叶的本质是植物，无论是干茶叶还是湿茶叶都应进入湿垃圾桶。然而，如果你喝的是袋泡茶，参考茶包咖啡包的处理方法。\n中药药渣同理。包括罗汉果、金银花、八角、桂皮等。",
          "link": ["茶包咖啡包", "咖啡渣"],
          "scene": ""
        }, {
          "name": "宠物食品",
          "englishName": "chongwushipin",
          "shareImgUrl": "http://i2.tiimg.com/693828/9465023ea7eb7bfa.jpg",
          "imgUrl": "../../images/household/chongwushipin.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "宠物食品如猫粮、狗粮、罐头等都是有机健康的，和人吃的食物没有本质区别。无论干粮或湿粮，请将他们作为湿垃圾处理。",
          "link": ["猫砂屎"],
          "scene": ""
        }, {
          "name": "蛋糕饼干",
          "englishName": "dangaobinggan",
          "shareImgUrl": "http://i2.tiimg.com/693828/cf25d881595b019a.jpg",
          "imgUrl": "../../images/household/dangaobinggan.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "蛋糕、饼干等烘焙类食品都是湿垃圾，无论他们看起来有多硬多干。",
          "link": ["面包"],
          "scene": ""
        }, {
          "name": "蛋壳",
          "englishName": "danke",
          "shareImgUrl": "http://i2.tiimg.com/693828/6562497a9d1b73ac.jpg",
          "imgUrl": "../../images/household/danke.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "作为食物废料的一员，蛋壳也是湿垃圾。\n同理，虾蟹的壳也是湿垃圾。",
          "link": ["虾蟹"],
          "scene": ""
        }, {
          "name": "动物肉类",
          "englishName": "dongwuroulei",
          "shareImgUrl": "http://i2.tiimg.com/693828/ec1bf9af10bc33b8.jpg",
          "imgUrl": "http://i1.fuimg.com/693828/a9091e08f58571bd.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "平时下厨处理下来的肉类废料应直接丢进湿垃圾。\n如果它们的油脂含量过于丰富，请参考动物油脂的处理方法。",
          "link": ["动物油脂"],
          "scene": ""
        }, {
          "name": "动物油脂",
          "englishName": "dongwuyouzhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/c655d61ceed95300.jpg",
          "imgUrl": "../../images/household/dongwuyouzhi.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "动物内脏、脂肪、火锅底料等大量油脂类物体，最好先用猫砂、厨房吸油纸或其他吸收剂固化一部分液体放入干垃圾中。之后再将剩余的大部分油脂作为湿垃圾处理。\n请不要将油脂直接排入下水管或马桶中，它们可能会堵塞你的管道系统，也导致污水处理或化粪池系统出现问题。",
          "link": ["剩饭剩菜", "动物肉类"],
          "scene": ""
        }, {
          "name": "鸡骨",
          "englishName": "jigu",
          "shareImgUrl": "http://i2.tiimg.com/693828/7570200d991a3f44.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/e708c6ff02c2a120.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "作为动物骨骼的一员，鸡骨、鱼骨、虾壳、蟹壳都是湿垃圾。\n然而，大骨不同。",
          "link": ["鱼骨","大骨","虾蟹"],
          "scene": ""
        }, {
          "name": "坚果",
          "englishName": "jianguo",
          "shareImgUrl": "http://i2.tiimg.com/693828/9905b9734b746a5f.jpg",
          "imgUrl": "http://i1.fuimg.com/693828/e9168f4a1a3ee8eb.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "瓜子皮、开心果壳等吃剩下的坚果都不应该放入干垃圾，无论他们看起来多坚硬。",
          "link": ["零食包装袋","生米谷物"],
          "scene": ""
        }, {
          "name": "酱汁",
          "englishName": "jiangzhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/ae23313fafa8545c.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/9d791c61dc0532e7.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "酱汁的本质就是食物，显而易见，它是湿垃圾。\n你可以将少量不太粘稠的酱汁直接排入下水管。",
          "link": ["动物油脂","酱料瓶"],
          "scene": ""
        }, {
          "name": "咖啡渣",
          "englishName": "kafeizha",
          "shareImgUrl": "http://i2.tiimg.com/693828/72931f8448adff88.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/b651f12a21cc8047.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物","植物"],
          "solution": "手工冲煮、滴滤等咖啡提取后产生的咖啡渣请丢入湿垃圾，它们的本质是植物。如果有滤纸请丢入干垃圾。\n然而，如果你使用的是挂耳袋泡类咖啡，参考茶包咖啡包的处理方法。",
          "link": ["茶包及咖啡包"],
          "scene": ""
        }, {
          "name": "绿植",
          "englishName": "lvzhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/f7276ee07cfc44af.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/baa99f708fb91b47.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["植物"],
          "solution": "废弃的绿植、枝、鲜花是很好的养料，请将他们放入湿垃圾。",
          "link": ["泥土","鲜花","枝"],
          "scene": ""
        }, {
          "name": "面包",
          "englishName": "mianbao",
          "shareImgUrl": "http://i2.tiimg.com/693828/c0b2f3e18ebc69e1.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/f00aac8967fa063e.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "面包也属于湿垃圾，无论它们看起来多硬多干。",
          "link": ["蛋糕饼干"],
          "scene": ""
        }, {
          "name": "生米谷物",
          "englishName": "shengmiguwu",
          "shareImgUrl": "http://i2.tiimg.com/693828/44d8a07c71f63348.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/92a28774d64f0e4a.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "过期腐坏的生米、谷物类未经烹煮的粮食也是湿垃圾，它们极易发酵。\n如果你是个啤酒爱好者，建议可以自己动手试试精酿。 ",
          "link": ["坚果"],
          "scene": ""
        }, {
          "name": "剩饭剩菜",
          "englishName": "shengfanshengcai",
          "shareImgUrl": "http://i2.tiimg.com/693828/0d529941ae1051a4.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/ecbb8ec74352d8d6.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "所有正餐吃剩下的食物都可以丢入湿垃圾。剩菜剩饭包括但不限于剩肉、剩碎骨、剩米粒、剩蔬菜等。\n禁止将剩菜剩饭排入下水管或马桶中，暂时也不建议使用水槽垃圾处理器，它们可能会堵塞你的管道系统。",
          "link": ["动物油脂", "鸡骨","鱼骨","大骨","酱汁"],
          "scene": ""
        }, {
          "name": "蔬菜",
          "englishName": "shucai",
          "shareImgUrl": "http://i2.tiimg.com/693828/05df081978f21c3e.jpg",
          "imgUrl": "http://i1.fuimg.com/693828/4e6139300380cf4b.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物","植物"],
          "solution": "平时下厨处理下来的蔬菜废料不可以丢进干垃圾，即使它们可能是干的。",
          "link": ["动物油脂","蛋壳","动物肉类"],
          "scene": ""
        }, {
          "name": "水果及其果皮",
          "englishName": "shuiguojiqiguopi",
          "shareImgUrl": "http://i2.tiimg.com/693828/b03c60bdfa3a6527.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/e8218e36744a7e0f.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "绝大部分腐烂的水果、吃剩的水果都可以作为湿垃圾处理。\n它们的果皮也扔进湿垃圾，除非是椰壳、榴莲壳、甘蔗皮。",
          "link": ["椰壳", "榴莲壳", "甘蔗皮"],
          "scene": ""
        }, {
          "name": "虾蟹",
          "englishName": "xiaxie",
          "shareImgUrl": "http://i2.tiimg.com/693828/06f1cd2e33325a66.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/5084a18d86c8725e.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "作为动物骨骼的一员，鸡骨、鱼骨、虾壳、蟹壳都是湿垃圾。\n别再相信抖机灵的文章了，小龙虾、帝王蟹的壳也是湿垃圾。然而，大骨不同。",
          "link": ["鸡骨", "鱼骨", "大骨"],
          "scene": ""
        }, {
          "name": "鲜花",
          "englishName": "xianhua",
          "shareImgUrl": "http://i2.tiimg.com/693828/c2cc12d9969bee72.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/58de8d0ffd6643c5.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["植物"],
          "solution": "也许你不喜欢那个鼓起勇气对你表白的人，但是对方送的鲜花请不要随便扔。\n废弃的绿植、枝、鲜花是很好的养料，请将他们拿回社区再放入湿垃圾桶。 ",
          "link": ["绿植", "枝"],
          "scene": ""
        }, {
          "name": "鱼骨",
          "englishName": "yugu",
          "shareImgUrl": "http://i2.tiimg.com/693828/b36d4ccb3cfe54f8.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/bf75bd2018af00d3.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["食物"],
          "solution": "作为动物骨骼的一员，鸡骨、鱼骨、虾壳、蟹壳都是湿垃圾。\n然而，大骨不同。",
          "link": ["鸡骨","大骨","虾蟹"],
          "scene": ""
        }, {
          "name": "枝",
          "englishName": "zhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/b5c10b5928e99622.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/3cc6065c6e2596c5.jpg",
          "copyright": "",
          "type": "湿垃圾",
          "material": ["植物"],
          "solution": "废弃的绿植、枝、鲜花是很好的养料，请将他们拿回社区再放入湿垃圾桶。\n剪下的枝条姿态各异，捆绑起来或直接插入花瓶作为装饰其实也很好看。",
          "link": ["绿植","鲜花","泥土"],
          "scene": ""
        }
      ]
    },
    {
      "num": 8,
      "iconUrl": "garbage.svg",
      "englishName": "garbage",
      "chineseName": "干垃圾",
      "description": "即普通垃圾，指除可回收物、有害垃圾、湿垃圾以外的其他生活废弃物。",
      "backgroundColor": "#CFE4F8",
      "list": [
        {
          "name": "白炽灯",
          "englishName": "baizhideng",
          "shareImgUrl": "https://i2.tiimg.com/693828/bf99f21600b2e9f0.jpg",
          "imgUrl": "../../images/garbage/baizhideng.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["玻璃"],
          "solution": "白炽灯是有灯丝、只能发射黄色暖光的灯泡，它们不是有害垃圾、也不方便回收。将破损或烧坏的灯泡包裹之后放在干垃圾中。\n荧光灯的处理方式不同",
          "link": ["荧光灯", "碎玻璃"],
          "scene": ""
        }, {
          "name": "保鲜膜",
          "englishName": "baoxianmo",
          "shareImgUrl": "https://i2.tiimg.com/693828/bb1a4c630d81a9da.jpg",
          "imgUrl": "../../images/garbage/baoxianmo.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "用过的、没有用过的保鲜膜都应该进入干垃圾。\n然而，它们的带齿包装盒可以回收。\n冰箱保鲜袋同此处理方式。",
          "link": ["塑料袋"],
          "scene": ""
        }, {
          "name": "笔",
          "englishName": "bi",
          "shareImgUrl": "https://i2.tiimg.com/693828/b198806cf03607ab.jpg",
          "imgUrl": "../../images/garbage/bi.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "木","金属"],
          "solution": "水笔、圆珠笔、铅笔等所有类型的笔都不可以被回收。\n尽量选择可替换内芯的笔书写，并将笔墨用完再考虑丢弃。\n与笔类似的化妆刷、眉笔等化妆用品也不可以回收。",
          "link": ["剪刀", "美工刀及其刀片", "尺子", "夹子", "胶带"],
          "scene": ""
        }, {
          "name": "茶包及咖啡包",
          "englishName": "chabaojikafeibao",
          "shareImgUrl": "https://i2.tiimg.com/693828/18b3d97c7ef812c3.jpg",
          "imgUrl": "../../images/garbage/chabaokafeibao.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸","棉布","食物"],
          "solution": "你愿意的话可以剪开茶包分离纸包和茶渣。不然的话，就把它们一起丢进干垃圾就完事儿。",
          "link": ["茶叶", "咖啡渣"],
          "scene": ""
        }, {
          "name": "打火机",
          "englishName": "dahuoji",
          "shareImgUrl": "https://i2.tiimg.com/693828/21a1d920a7f50e64.jpg",
          "imgUrl": "../../images/garbage/dahuoji.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料","金属"],
          "solution": "不是有害垃圾，无论金属还是塑料，都不要回收，不要暴力投放，否则可能引起爆炸。",
          "link": ["烟蒂"],
          "scene": ""
        }, {
          "name": "大骨",
          "englishName": "dagu",
          "shareImgUrl": "https://i2.tiimg.com/693828/2ab908a6bfc43488.jpg",
          "imgUrl": "../../images/garbage/dagu.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["食物"],
          "solution": "作为动物骨骼的一员，大骨很不争气的被湿垃圾除名。它太过坚硬，所以会对处理的机器产生非常大的破坏。\n它应该作为干垃圾处理，处理前将上面残余的脂肪大致清除。\n如果你有养狗，也许它会很喜爱你手上的这根大骨，不如交给它处理吧。",
          "link": ["鸡骨","鱼骨","虾壳","蟹壳"],
          "scene": ""
        }, {
          "name": "防碎气泡膜",
          "englishName": "fangsuiqipaomo",
          "shareImgUrl": "https://i2.tiimg.com/693828/04ec29ab9752a45e.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/8f62e0b74876db89.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "不可回收。建议作为礼品包装重复使用。",
          "link": ["泡沫塑料", "快递纸板箱", "快递信封纸袋"],
          "scene": ""
        }, {
          "name": "服装吊牌",
          "englishName": "fuzhuangdiaopai",
          "shareImgUrl": "https://i2.tiimg.com/693828/5f0e997f79ae8439.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/f2a9a5d0e10ee828.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸", "塑料"],
          "solution": "服装吊牌的材质复杂，不可回收。\n时尚品牌应该思考自己对环保的贡献，减少吊牌的使用或运用完全天然的材质生产它们。",
          "link": ["旧鞋", "旧衣","旧裤子","旧帽子","旧包"],
          "scene": ""
        }, {
          "name": "甘蔗皮",
          "englishName": "ganzhepi",
          "shareImgUrl": "https://i2.tiimg.com/693828/f78b348c8d21b6db.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/9d4c1f633f45dd84.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["食物"],
          "solution": "不是湿垃圾！\n甘蔗皮实在太过尖锐、吃甘蔗时，如果产生了甘蔗皮，把它们丢入干垃圾，嚼过的甘蔗渣丢入湿垃圾。",
          "link": ["水果及果皮","椰壳","榴莲壳"],
          "scene": ""
        }, {
          "name": "钢丝球",
          "englishName": "gangsiqiu",
          "shareImgUrl": "https://i2.tiimg.com/693828/3f385ce34497c288.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/ef1ca4563a403108.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["金属"],
          "solution": "富婆快乐球，它因为沾了太多的脏东西，因此不可回收。",
          "link": ["橡胶手套"],
          "scene": ""
        }, {
          "name": "膏药贴",
          "englishName": "gaoyaotie",
          "shareImgUrl": "https://i2.tiimg.com/693828/36989d1cd6b406bd.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/1399a44b24aa7c63.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "化学品"],
          "solution": "不要回收！但也不是有害垃圾！\n居民区有害垃圾产量小、所以清运频率远低于干垃圾，这类物品在社区贮存也有卫生隐患。所以，家庭零星产生的棉签、纱布、创可贴之类的，尤其是注射器建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到干垃圾桶，被安全焚烧掉。",
          "link": ["纱布", "棉签", "酒精棉"],
          "scene": ""
        }, {
          "name": "灰尘",
          "englishName": "huicheng",
          "shareImgUrl": "https://i2.tiimg.com/693828/8472810adc0b97bb.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/eda5979a0647239c.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["复杂质"],
          "solution": "灰尘的成分复杂，可作为干垃圾处理。 必须完全冷却、沾湿、装箱或装袋。",
          "link": ["泥土", "毛发", "猫砂屎"],
          "scene": ""
        }, {
          "name": "回形针和订书钉",
          "englishName": "huixingzheng",
          "shareImgUrl": "https://i2.tiimg.com/693828/0e209d57ebc69e20.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/43d6646fb6d1874d.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["金属"],
          "solution": "不可回收！\n如有需要，回形针可以再利用做成小挂钩。",
          "link": ["五金工具及螺丝", "办公纸", "夹子"],
          "scene": ""
        }, {
          "name": "碱性电池",
          "englishName": "jianxingdianchi",
          "shareImgUrl": "https://i2.tiimg.com/693828/aa115c65904e845b.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/9fbb42ea5980c348.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["电子"],
          "solution": "家用碱性电池可以直接放入干垃圾，它们不再含有危险化合物。\n然而还是鼓励使用可充电电池来减少浪费！",
          "link": ["纽扣电池", "充电电池", "手机电池"],
          "scene": ""
        }, {
          "name": "胶带",
          "englishName": "jiaodai",
          "shareImgUrl": "https://i2.tiimg.com/693828/ddb961f1109eb230.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/b884b603c4f60ec0.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["橡胶"],
          "solution": "手工达人会产出部分的胶带，请将他们丢入干垃圾即可。\n网购达人们请注意，因为胶带上的胶会黏住加工的机器致使纸箱回收困难。所以在拆完快递后，请先撕掉纸箱上的胶带，将胶带投入干垃圾。",
          "link": ["胶水","剪刀","美工刀及其刀片","纸板箱"],
          "scene": ""
        }, {
          "name": "胶水",
          "englishName": "jiaoshui",
          "shareImgUrl": "https://i2.tiimg.com/693828/a7c0f63d3ee8a97a.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/79790a436cef1b60.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "化学品"],
          "solution": "不要回收！不是有害垃圾！",
          "link": ["胶带", "办公纸"],
          "scene": ""
        }, {
          "name": "镜子",
          "englishName": "jingzi",
          "shareImgUrl": "https://i2.tiimg.com/693828/ffdef0c8dfcaed0f.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/f5e72a7fd23820c7.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["玻璃", "金属", "塑料"],
          "solution": "捐赠或转售闲置的镜子。\n实在不行，就放入干垃圾，破碎的镜子务必将碎片包好后投放。",
          "link": ["碎玻璃"],
          "scene": ""
        }, {
          "name": "酒精棉",
          "englishName": "jiujingmian",
          "shareImgUrl": "https://i2.tiimg.com/693828/ad3ddcd304a764e0.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/6dc6f125e3441ec8.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布", "化学品"],
          "solution": "不要回收！用过的酒精棉也不是有害垃圾！\n居民区有害垃圾产量小、所以清运频率远低于干垃圾，这类物品在社区贮存也有卫生隐患。所以，家庭零星产生的棉签、纱布、创可贴之类的，尤其是注射器建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到干垃圾桶，被安全焚烧掉。",
          "link": ["棉签", "纱布", "膏药贴"],
          "scene": ""
        }, {
          "name": "口红管",
          "englishName": "kouhongguan",
          "shareImgUrl": "https://i2.tiimg.com/693828/b9e94cd4cbdd139e.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/80f65261c09a65c3.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "化学品"],
          "solution": "口红是无害的，但不同于普通化妆品容器，它的化学残余物很难被清除干净，所以将它丢入干垃圾桶吧。",
          "link": ["化妆品容器", "指甲油及容器"],
          "scene": ""
        }, {
          "name": "口香糖",
          "englishName": "kouxiangtang",
          "shareImgUrl": "https://i2.tiimg.com/693828/63bac48cedaab340.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/9a83a730d6270b72.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["橡胶","食物"],
          "solution": "口香糖的本质是胶、请投入干垃圾。处理前，请先用纸包裹完好。",
          "link": [""],
          "scene": ""
        }, {
          "name": "快递塑料袋",
          "englishName": "kuaidisuliaodai",
          "shareImgUrl": "https://i2.tiimg.com/693828/6aca6f2e6002b8cd.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/48a01215ea845a2e.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "不要回收！制作快递塑料袋的材料不适宜被再次利用。",
          "link": ["塑料袋", "防碎气泡膜", "快递纸板箱", "快递信封纸袋"],
          "scene": ""
        }, {
          "name": "垃圾袋",
          "englishName": "lajidai",
          "shareImgUrl": "http://i2.tiimg.com/693828/250cbe3e68499460.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/b09e24e53d88e1c5.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "垃圾袋应该进入干垃圾桶，没毛病！",
          "link": ["塑料袋", "纸袋"],
          "scene": ""
        }, {
          "name": "零食包装袋",
          "englishName": "lingshibaozhuangdai",
          "shareImgUrl": "http://i2.tiimg.com/693828/7bae71dac544cbf5.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/6c6945a23f21bb71.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "不要回收利用。\n包装薯片、饼干、瓜子等零食的铝箔包装袋通常含有食物残渣和水分，污染其余的材料。",
          "link": ["奶茶外带杯", "酸奶罐", "利乐纸盒", "纸质包装盒", "饮料易拉罐", "金属罐", "口香糖"],
          "scene": ""
        }, {
          "name": "榴莲壳",
          "englishName": "liulianke",
          "shareImgUrl": "http://i2.tiimg.com/693828/905cb4e01db2885e.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/ed8c8d7d1c7232bf.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["食物"],
          "solution": "不是湿垃圾！\n榴莲壳实在太过坚硬、吃完榴莲，记得把榴莲壳丢进干垃圾。",
          "link": ["水果及果皮", "椰壳", "甘蔗皮"],
          "scene": ""
        }, {
          "name": "猫砂屎",
          "englishName": "maoshashi",
          "shareImgUrl": "http://i2.tiimg.com/693828/86252264b0f0fafe.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/54533599ee4c9db3.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["复杂质"],
          "solution": "最好将宠物的屎混合猫砂一起丢入干垃圾中，它们不能被用来填埋堆肥\n除非是百分百豆腐猫砂，不然不要将猫砂冲入马桶中。",
          "link": ["宠物食品", "灰尘", "毛发"],
          "scene": ""
        }, {
          "name": "毛发",
          "englishName": "maofa",
          "shareImgUrl": "http://i2.tiimg.com/693828/eecf029002529e26.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/f16d37bc8ac1199e.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["复杂质"],
          "solution": "平时掉落的发丝、宠物毛发、皮屑、指甲连同灰尘一起放入干垃圾。最好沾湿、成团，避免再次飘到空气中。",
          "link": ["灰尘"],
          "scene": ""
        }, {
          "name": "毛巾",
          "englishName": "maojing",
          "shareImgUrl": "http://i2.tiimg.com/693828/30877fbb9ae8f942.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/e30d49568aac1f31.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布"],
          "solution": "毛巾应不可避免与人体产生过度亲密而列为干垃圾。废弃毛巾鼓励作为抹布重复使用。",
          "link": ["抹布", "家纺"],
          "scene": ""
        }, {
          "name": "棉签",
          "englishName": "mianqian",
          "shareImgUrl": "http://i2.tiimg.com/693828/0b2f66f0d940197b.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/c6a8639f36e4ddb2.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料","棉布"],
          "solution": "不是有害垃圾！\n区民区有害垃圾产量小、所以清运频率远低于干垃圾，这类物品在社区贮存也有卫生隐患。所以，家庭零星产生的棉签、纱布、创可贴之类的，尤其是注射器建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到干垃圾桶，被安全焚烧掉。",
          "link": ["纱布", "膏药贴", "酒精棉", "牙签竹签"],
          "scene": ""
        }, {
          "name": "抹布",
          "englishName": "mabu",
          "shareImgUrl": "http://i2.tiimg.com/693828/64a7f68afa09cb8f.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/7b062df236c73eec.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布"],
          "solution": "不要回收！用过的抹布实在是含有太多细菌了，但他也不是有害垃圾。",
          "link": ["毛巾", "湿纸巾", "纱布"],
          "scene": ""
        }, {
          "name": "奶茶外带杯",
          "englishName": "naichawaidaibei",
          "shareImgUrl": "http://i2.tiimg.com/693828/dc43f27fb45dfddf.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/b3c37cb8bc580b46.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "纸"],
          "solution": "不要回收！\n塑料奶茶杯、盖这类薄型塑料其实回收利用价值都极低，而且沾染了油脂很容易污染其他可回收物。而纸质的奶茶杯则因含有防水涂层更不符合回收标准。\n倒入干垃圾桶之前，先将内部液体清空。",
          "link": ["软塑料盒", "饮料塑料瓶", "利乐纸盒", "纸杯"],
          "scene": ""
        }, {
          "name": "内衣裤",
          "englishName": "neiyiku",
          "shareImgUrl": "http://i2.tiimg.com/693828/958cb210bbb85f87.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/0c33ec5451592985.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布"],
          "solution": "内衣裤应不可避免与人体产生过度亲密而列为干垃圾。原味内裤还是直接放入干垃圾吧。",
          "link": ["旧裤子"],
          "scene": ""
        }, {
          "name": "泥土",
          "englishName": "nitu",
          "shareImgUrl": "http://i2.tiimg.com/693828/2c53921f8c35d2b6.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/7c22edda32f8a7b7.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["复杂质"],
          "solution": "养绿植产生的泥土不可以作为湿垃圾处理！通常它们受污染的程度非常严重。",
          "link": ["绿植", "枝", "鲜花", "灰尘"],
          "scene": ""
        }, {
          "name": "软塑料盒",
          "englishName": "ruansuliaoke",
          "shareImgUrl": "http://i2.tiimg.com/693828/fdbb646f0c164384.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/60598b30739aabff.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "如水果塑料盒之类的薄软塑料容器都不可回收，更不要提被污染过的塑料餐盒了。",
          "link": ["硬塑料盒", "奶茶外带杯", "饮料塑料瓶", "食品包装袋", "外卖餐盒"],
          "scene": ""
        }, {
          "name": "软药膏",
          "englishName": "ruanyaogao",
          "shareImgUrl": "http://i2.tiimg.com/693828/3f530791037d5025.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/12d6dd3b11a5e670.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "化学品"],
          "solution": "不是有害垃圾！\n软膏制剂药品，应将药膏从容器中挤出，收集在信封内，封好后和管壳一起丢入干垃圾。",
          "link": ["药品及其包装", "咳嗽药水及其包装"],
          "scene": ""
        }, {
          "name": "纱布",
          "englishName": "shabu",
          "shareImgUrl": "http://i2.tiimg.com/693828/6d9339646e41cec9.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/d3bd37150ec595d7.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布","化学品"],
          "solution": "不要回收！浸泡过药水的纱布也不是有害垃圾！居民区有害垃圾产量小、所以清运频率远低于干垃圾，这类物品在社区贮存也有卫生隐患。\n所以，家庭零星产生的棉签、纱布、创可贴之类的，尤其是注射器建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到干垃圾桶，被安全焚烧掉。",
          "link": ["棉签", "膏药贴", "抹布"],
          "scene": ""
        }, {
          "name": "湿纸巾",
          "englishName": "shizhijing",
          "shareImgUrl": "http://i2.tiimg.com/693828/d30f524253c2ced4.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/fc7f4b612a907739.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["棉布","化学品"],
          "solution": "用过的湿纸巾含有大量细菌，不可回收。虽然是湿的，但它的材质只允许它被放入干垃圾。同时，包装湿纸巾的包装袋也是干垃圾",
          "link": ["纸巾", "酒精棉", "抹布", "纱布"],
          "scene": ""
        }, {
          "name": "手机壳",
          "englishName": "shoujike",
          "shareImgUrl": "http://i2.tiimg.com/693828/9388336327a72da1.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/e5d32b6a7f8eb901.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "橡胶"],
          "solution": "回收价值低，不要回收。\n对于闲置的手机壳，鼓励转售或赠与。",
          "link": ["旧手机"],
          "scene": ""
        }, {
          "name": "塑料袋",
          "englishName": "suliaodai",
          "shareImgUrl": "http://i2.tiimg.com/693828/cee70ba6e5958ca3.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/527d203622b9d88c.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "不要回收！\n塑料袋会分解成塑料微粒、杀死野生动物。尽管我们希望这些塑料袋会和我们其他的回收品一起被送往处理厂，但不应如此。它们会堵塞机器，变成废品管理员的噩梦。\n请帮助减少浪费，重复使用帆布购物袋进行购物。",
          "link": ["垃圾袋", "快递塑料袋", "纸袋"],
          "scene": ""
        }, {
          "name": "陶瓷器皿",
          "englishName": "taociqimin",
          "shareImgUrl": "http://i2.tiimg.com/693828/e7b1b3cc28136f7e.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/c56f4150ef638fbc.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["陶瓷"],
          "solution": "瓷器只有当完好的时候才有价值，废弃的陶瓷产品其实是不可回收的。\n闲置的可以收藏或转售，考虑重复利用的可能。\n陶土花盆同此处理方法。碎瓷片请确保包裹完整后再处理。",
          "link": ["塑料餐具", "玻璃器皿", "金属餐具", "碎玻璃"],
          "scene": ""
        }, {
          "name": "外卖餐盒",
          "englishName": "waimaicanhe",
          "shareImgUrl": "http://i2.tiimg.com/693828/c62a112879b50d86.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/a5ab41150a87f057.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸", "塑料", "食物"],
          "solution": "经常吃外卖的你千万不要回收你的餐盒，不管它是塑料还是纸。\n油污是最常见的污染源，它的问题在于，油常常会渗入硬纸板。这种油无法与纤维分离，导致纤维的价值降低，更难出售。更不要提你没有处理干净的食物残留了：剩在塑料盒里的几粒米饭或菜叶。\n清洗掉这些外卖盒里的食物残留非常重要，因为即使在干垃圾中，过多的食物和液体残留也会使一大批废品都收到污染，从而无法正常焚烧。",
          "link": ["软塑料盒", "一次性餐具", "牙签竹签", "动物油脂", "剩菜剩饭", "虾蟹", "大骨", "鸡骨", "鱼骨", "酱汁"],
          "scene": ""
        }, {
          "name": "卫生巾",
          "englishName": "weishengjing",
          "shareImgUrl": "http://i2.tiimg.com/693828/4effff5628536fe1.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/162f0f6cce38b8db.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "无论使用还是未使用过的，都不可回收，也不可放入湿垃圾。\n不要直接将用过的卫生巾丢入马桶，它毫无疑问会堵塞你的管道系统。",
          "link": ["纸尿裤", "安全套"],
          "scene": ""
        }, {
          "name": "卫生纸",
          "englishName": "weishengzhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/d887150120de8510.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/22c1c40ba16082c5.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "厕纸、卫生纸、厨房吸油纸，无论净或脏，不要回收！也不要丢入湿垃圾！你应该把它们投入干垃圾桶。\n同时，卷筒卫生纸的纸芯是可以回收的。包装用的薄塑料袋因回收价值极低，属于干垃圾。\n值得一提的是，所有供如厕使用的卫生纸都是可以冲入马桶的。",
          "link": ["纸巾", "卷筒纸芯"],
          "scene": ""
        }, {
          "name": "污损纸张",
          "englishName": "wusunzhizhang",
          "shareImgUrl": "http://i2.tiimg.com/693828/d12b18427f0705b9.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/e371e67fd0b70f01.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "不要回收！虽然是可以写字的办公类纸张，但一旦被污染并折损，就应该丢入干垃圾。",
          "link": ["办公纸", "纸屑", "纸巾", "干净报纸", "卫生纸"],
          "scene": ""
        }, {
          "name": "橡胶手套",
          "englishName": "xiangjiaoshoutao",
          "shareImgUrl": "http://i2.tiimg.com/693828/5fcaa7b5907fdea2.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/06988747e1a5dd72.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["橡胶"],
          "solution": "不可回收。因为其受污染严重，且难以清理。",
          "link": ["钢丝球"],
          "scene": ""
        }, {
          "name": "牙签竹签",
          "englishName": "yaqianzhuqian",
          "shareImgUrl": "http://i2.tiimg.com/693828/8c9e0a57e9a4ecf8.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/037a2c66aa331841.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["木"],
          "solution": "用过的竹签与牙签与人的口腔有过亲密接触，且价值极低，故不可回收。",
          "link": ["一次性餐具", "棉签"],
          "scene": ""
        }, {
          "name": "牙刷牙膏",
          "englishName": "yashuayagao",
          "shareImgUrl": "http://i2.tiimg.com/693828/dd9861f22d6e229d.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/aa1210e406ff1cf8.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "化学品"],
          "solution": "牙刷建议投放到干垃圾里，因为它和人体曾亲密接触，且牙刷前端的成分并不是塑料，而是复合材料。对于牙膏管，因为其内部的内容物很难完全清洁，所以也应投放到干垃圾里。",
          "link": ["化妆品容器", "化妆刷", "口红管", "洗发水容器", "药膏"],
          "scene": ""
        }, {
          "name": "烟蒂",
          "englishName": "yandi",
          "shareImgUrl": "http://i2.tiimg.com/693828/1d6e9f0703594415.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/6b16ed16f77b365e.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["植物", "纸"],
          "solution": "请保证烟头已完全熄灭然后丢入干垃圾，它们不是有害垃圾但是对你的身体有害。",
          "link": ["打火机"],
          "scene": ""
        }, {
          "name": "眼镜",
          "englishName": "yanjing",
          "shareImgUrl": "http://i2.tiimg.com/693828/1f5fc72c4edcf0fd.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/d2152f43278a928d.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["玻璃", "金属", "木"],
          "solution": "联系当地的眼镜商或公益组织，他们也许会收集旧眼镜，将镜片与框架重新研磨并送给有需要的人。眼镜盒材质复杂，也归为干垃圾一类。\n除此以外，将它们丢入干垃圾桶，不可被用来回收。",
          "link": ["隐形眼镜"],
          "scene": ""
        }, {
          "name": "椰壳",
          "englishName": "yeke",
          "shareImgUrl": "http://i2.tiimg.com/693828/9e36fcc4b8996ea7.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/be6195a0ad77472f.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["食物"],
          "solution": "不是湿垃圾！\n椰壳实在太过坚硬、喝完椰汁，记得把椰壳和吸管丢进干垃圾。你也没有必要特地把内部的椰肉分离出来。",
          "link": ["水果及果皮", "榴莲壳","甘蔗皮"],
          "scene": ""
        }, {
          "name": "一次性餐具",
          "englishName": "yicixingcanju",
          "shareImgUrl": "http://i2.tiimg.com/693828/fd1d73c7ea58484c.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/455eb800c125bc4c.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "纸", "木"],
          "solution": "不要回收！\n无论是纸碗、纸杯、纸盘、吸管、一次性竹筷等，在用餐后沾染了油污都将成为回收过程中重要的污染源。请随身携带筷子并使用自己的马克杯或可清洗的碗碟来减少浪费。",
          "link": ["塑料餐具", "纸杯", "外卖餐盒", "金属餐具", "牙签竹签", "木质餐具", "瓷餐具"],
          "scene": ""
        }, {
          "name": "隐形眼镜",
          "englishName": "yinxingyanjing",
          "shareImgUrl": "http://i2.tiimg.com/693828/4cc3981772790422.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/036b53cded3976fa.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料"],
          "solution": "不是湿垃圾！隐形眼镜虽然是湿的，但是脱水后就是一个小塑料片。不要回收！回收价值极低。\n同时，装隐形眼镜的一次性包装盒与盒子均属于干净塑料盒的范畴、护理液容器属于洗浴品容器范畴。它们是可回收物。",
          "link": ["眼镜","干净塑料盒", "洗浴品容器"],
          "scene": ""
        }, {
          "name": "用过的安全套",
          "englishName": "yongguodeanquantao",
          "shareImgUrl": "https://i2.tiimg.com/693828/dd4286133aa00a0f.jpg",
          "imgUrl": "../../images/garbage/anquantao.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["橡胶", "塑料"],
          "solution": "用过的安全套请尽量沥干内部液体后丢弃，不要重复利用。\n包装的铝箔袋也是干垃圾。",
          "link": ["卫生巾"],
          "scene": ""
        }, {
          "name": "羽毛球及球拍",
          "englishName": "yumaoqiujiqiupai",
          "shareImgUrl": "http://i2.tiimg.com/693828/e45934bf68fb7629.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/8fb160ca9524f871.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["塑料", "金属"],
          "solution": "不便于回收利用，损坏的球拍应与球一起丢入干垃圾桶。",
          "link": ["足球", "玩具"],
          "scene": ""
        }, {
          "name": "纸杯",
          "englishName": "zhibei",
          "shareImgUrl": "http://i2.tiimg.com/693828/9bf429dfb17a11e9.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/1a54e0a97623f8ef.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "所有的一次性纸杯都应放入干垃圾，因为它们大多都有一层防水涂料。\n尽量使用可重复利用的容器。",
          "link": ["奶茶外带杯", "一次性餐具", "利乐纸盒"],
          "scene": ""
        }, {
          "name": "纸巾",
          "englishName": "zhijing",
          "shareImgUrl": "http://i2.tiimg.com/693828/6ecef1d9786f431a.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/0ea95ae8c25eea95.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "无论净或脏，不要回收！也不要丢入湿垃圾！你应该把它们投入干垃圾桶。\n使用手帕来减少纸张浪费是更好的选择，也会让你更有风度。\n同时，包装纸巾的纸盒是可以回收的。",
          "link": ["湿纸巾", "污损纸张", "厕纸", "办公纸", "纸屑", "卷筒纸芯", "纸质包装盒"],
          "scene": ""
        }, {
          "name": "纸尿裤",
          "englishName": "zhiniaoku",
          "shareImgUrl": "http://i2.tiimg.com/693828/c956222338d5ccf7.jpg",
          "imgUrl": "https://i1.fuimg.com/693828/0c1e8500ee87108a.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "无论净或脏，使用过的纸尿裤都应投入干垃圾。\n若你的婴儿已经长大，转赠未使用过的纸尿裤会是一个很棒的选择。",
          "link": ["卫生巾", "猫砂屎"],
          "scene": ""
        }, {
          "name": "纸屑",
          "englishName": "zhixue",
          "shareImgUrl": "http://i2.tiimg.com/693828/516329af16a3dad4.jpg",
          "imgUrl": "http://i1.fuimg.com/693828/523cab12596a53b5.jpg",
          "copyright": "",
          "type": "干垃圾",
          "material": ["纸"],
          "solution": "纸屑以及碎纸机处理过的碎纸已降低了纤维的质量，故不可回收。",
          "link": ["办公纸", "无损纸张"],
          "scene": ""
        }
      ]
    },
    {
      "num": 3,
      "iconUrl": "hazardous.svg",
      "englishName": "hazardous",
      "chineseName": "有害垃圾",
      "description": "指废电池、废灯管、废药品、废油漆及其容器等对人体健康或自然环境造成危害的生活废弃物。",
      "backgroundColor": "#FFCED4",
      "list": [
        {
          "name": "充电电池",
          "englishName": "chongdiandianchi",
          "shareImgUrl": "http://i2.tiimg.com/693828/954193f14ded3e00.jpg",
          "imgUrl": "../../images/hazardous/chongdiandianchi.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["电子"],
          "solution": "可充电电池可用于笔记本电脑、数码相机、电动牙刷和遥控玩具等。所以在处理上述电子物品时，最好将它们的电池取出来作为有害垃圾处理。\n碱性电池不是有害垃圾，但仍然建议你用充电电池替代碱性电池，因为任何可重复使用的东西都是环保的。",
          "link": ["纽扣电池", "碱性电池", "手机电池"],
          "scene": ""
        }, {
          "name": "咳嗽药水及其包装",
          "englishName": "kesouyaoshui",
          "shareImgUrl": "http://i2.tiimg.com/693828/0189f70ad55bc26c.jpg",
          "imgUrl": "../../images/hazardous/kesouyaoshui.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["化学品", "塑料", "玻璃", "纸"],
          "solution": "为防止滥用药物和污染环境，请不要将残留药物丢弃在垃圾桶或排水管中。\n建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到有害垃圾桶。处理前请盖紧盖子或包裹完好。 ",
          "link": ["药品及其包装", "药膏"],
          "scene": ""
        }, {
          "name": "纽扣电池",
          "englishName": "niukoudianchi",
          "shareImgUrl": "http://i2.tiimg.com/693828/29db15663474a25c.jpg",
          "imgUrl": "../../images/hazardous/niukoudianchi.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["电子"],
          "solution": "纽扣电池（可在手表、助听器、相机中找到）可能含有极少量的银和汞。\n许多手表、珠宝和照相馆也许在回收它们。若没有上述的渠道地点，直接把它们当做有害垃圾处理。",
          "link": ["充电电池", "碱性电池", "手机电池"],
          "scene": ""
        }, {
          "name": "杀虫喷雾罐",
          "englishName": "shachong",
          "shareImgUrl": "http://i2.tiimg.com/693828/00bf43d6b29b01a3.jpg",
          "imgUrl": "../../images/hazardous/shachongpengwuguan.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["金属", "化学品"],
          "solution": "危害程度堪比农药。\n虽然你可以将用不完的杀虫剂放入有害垃圾，但这类有害垃圾处理起来仍然是非常的不便。十分建议你把剂体全部用完后再扔。",
          "link": ["消毒水容器", "油漆桶"],
          "scene": ""
        }, {
          "name": "手机电池",
          "englishName": "shoujidianchi",
          "shareImgUrl": "http://i2.tiimg.com/693828/f3d9f35b169cfe30.jpg",
          "imgUrl": "../../images/hazardous/shoujidianchi.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["电子"],
          "solution": "性质同充电电池。\n可充电电池可用于手机、笔记本电脑、数码相机、电动牙刷和遥控玩具等。所以在处理上述电子物品时，最好将它们的电池取出来作为有害垃圾处理。\n碱性电池不是有害垃圾，但仍然建议你用充电电池替代碱性电池，因为任何可重复使用的东西都是环保的。 ",
          "link": ["充电电池", "纽扣电池","碱性电池"],
          "scene": ""
        }, {
          "name": "温度计",
          "englishName": "wenduji",
          "shareImgUrl": "http://i2.tiimg.com/693828/7c61416b733c27e1.jpg",
          "imgUrl": "../../images/hazardous/wenduji.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["玻璃", "化学品"],
          "solution": "不要回收！不要放入干垃圾！\n汞是危险的，它可以伤害神经、消化系统和呼吸系统以及肾脏。如果被处理不当，它可能会进入环境，损害鱼和水的质量。",
          "link": ["酒精棉", "荧光灯"],
          "scene": ""
        }, {
          "name": "相片",
          "englishName": "xiangpian",
          "shareImgUrl": "http://i2.tiimg.com/693828/61c1c2e2ee5eade0.jpg",
          "imgUrl": "../../images/hazardous/xiangpian.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["纸", "化学品"],
          "solution": "由于相片含有的化学品以及短纤维的材质，不要回收！甚至你应该将其放入有害垃圾中！",
          "link": [""],
          "scene": ""
        }, {
          "name": "消毒剂容器",
          "englishName": "xiaoduji",
          "shareImgUrl": "http://i2.tiimg.com/693828/3da105d40a0c9577.jpg",
          "imgUrl": "../../images/hazardous/xiaodujirongqi.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["塑料", "化学品"],
          "solution": "虽然大多数塑料容器可以回收，但是装有高浓度消毒剂的容器是有害垃圾，如洁厕灵。盖紧盖子并妥善投放。十分建议你把剂体全部用完后再扔。",
          "link": ["洗衣粉液瓶", "洗洁精容器", "杀虫喷雾罐"],
          "scene": ""
        }, {
          "name": "药品及其包装",
          "englishName": "yaopinjibaozhuang",
          "shareImgUrl": "http://i2.tiimg.com/693828/610654410e506091.jpg",
          "imgUrl": "../../images/hazardous/yaopin.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["化学品", "塑料", "纸"],
          "solution": "为防止滥用药物和污染环境，请不要将残留药物丢弃在垃圾桶或排水管中。\n建议投放到设有医废回收的药店医院。实在无法进行上述投放，那么就可以把他们投放到有害垃圾桶。处理前请盖紧盖子或包裹完好。",
          "link": ["咳嗽药水及其包装", "药膏"],
          "scene": ""
        }, {
          "name": "荧光灯",
          "englishName": "yinguangdeng",
          "shareImgUrl": "http://i2.tiimg.com/693828/a072562f39d33e4f.jpg",
          "imgUrl": "../../images/hazardous/yinguangdeng.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["玻璃", "化学品"],
          "solution": "几乎所有荧光灯都含有汞，它非常危险，禁止投入干垃圾！\n白炽灯的处理方式不同。",
          "link": ["白炽灯"],
          "scene": ""
        }, {
          "name": "油漆桶",
          "englishName": "youqitong",
          "shareImgUrl": "http://i2.tiimg.com/693828/7863ed2f64b0c581.jpg",
          "imgUrl": "../../images/hazardous/youqitong.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["金属", "化学品"],
          "solution": "所有涂料罐、油漆桶或喷漆罐都属于装修垃圾，在大多数社区，它们甚至不能被简单地投入有害垃圾桶。请咨询物业该将它们收集到什么地方。",
          "link": ["食品罐头", "金属盒", "杀虫喷雾罐"],
          "scene": ""
        }, {
          "name": "指甲油及其容器",
          "englishName": "zhijiayou",
          "shareImgUrl": "http://i2.tiimg.com/693828/8b33af21c1b0e5f6.jpg",
          "imgUrl": "../../images/hazardous/zhijiayou.jpg",
          "copyright": "",
          "type": "有害垃圾",
          "material": ["玻璃", "塑料", "化学品"],
          "solution": "指甲油、洗甲水和染发剂的瓶子不可回收！内容物也不要倒出，盖紧盖子放入有害垃圾桶就完事儿。\n有害垃圾的处理非常困难，十分建议你把剂体全部用完后再扔。",
          "link": ["化妆品容器", "口红管", "洗发水容器"],
          "scene": ""
        }
      ]
    },
    {
      "num": 1,
      "iconUrl": "recyclable.svg",
      "englishName": "recyclable",
      "chineseName": "可回收物",
      "description": "指废纸张、废塑料、废玻璃、废金属、废织物等适宜回收、可循环利用的生活废弃物。",
      "backgroundColor": "#CFE7E1",
      "list": [
        {
          "name": "办公纸",
          "englishName": "bangongzhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/e553ed606fc5bfef.jpg",
          "imgUrl": "../../images/recyclable/bangongzhi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "整洁的办公纸不应该放入干垃圾。\n请减少浪费，尽量使用双面打印，或在未打印的一面进行书写工作。\n揉成团的纸张参考「污损纸张」的处理方法。",
          "link": ["干净报纸", "污损纸张", "纸屑", "笔"],
          "scene": ""
        }, {
          "name": "玻璃器皿",
          "englishName": "boliqimin",
          "shareImgUrl": "http://i2.tiimg.com/693828/0e5a8634c6f6bfa8.jpg",
          "imgUrl": "../../images/recyclable/boliqimin.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["玻璃"],
          "solution": "玻璃杯、碗、盘、罐等闲置的玻璃器皿建议捐赠或转售。\n玻璃花瓶同此处理方法。如果破碎了也是可以回收的。\n总结，不要把它们当干垃圾丢了。",
          "link": ["碎玻璃", "啤酒瓶", "酱料瓶", "金属餐具", "木质餐具", "塑料餐具", "陶瓷餐具"],
          "scene": ""
        }, {
          "name": "菜刀",
          "englishName": "caidao",
          "shareImgUrl": "http://i2.tiimg.com/693828/7b510778cd7d849f.jpg",
          "imgUrl": "../../images/recyclable/caidao.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "木"],
          "solution": "可以回收。借助磨刀石可重复利用。",
          "link": ["美工刀及其刀片", "锅具", "砧板"],
          "scene": ""
        }, {
          "name": "插座",
          "englishName": "chazuo",
          "shareImgUrl": "http://i2.tiimg.com/693828/cf7faf95cdc598e3.jpg",
          "imgUrl": "../../images/recyclable/chazuo.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["电子", "塑料"],
          "solution": "要回收手机、笔记本电脑、键盘鼠标等这类小型电子产品请用「闲鱼」上门回收功能。  禁止这类产品出现在干垃圾中。  ",
          "link": ["电线"],
          "scene": ""
        }, {
          "name": "尺子",
          "englishName": "chizi",
          "shareImgUrl": "http://i2.tiimg.com/693828/108b1126d1fa8584.jpg",
          "imgUrl": "../../images/recyclable/chizi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "不是干垃圾。塑料尺、钢尺、卷尺都是可回收物！\n闲置物品请赠与或转售。",
          "link": ["美工刀及其刀片", "剪刀", "五金工具及螺丝", "胶水", "胶带", "纸屑", "笔"],
          "scene": ""
        }, {
          "name": "充电宝",
          "englishName": "chongdianbao",
          "shareImgUrl": "http://i2.tiimg.com/693828/7fb50dde5cc8f0eb.jpg",
          "imgUrl": "../../images/recyclable/chongdianbao.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["电子", "金属"],
          "solution": "要回收手机、笔记本电脑、键盘鼠标等这类小型电子产品请用「闲鱼」上门回收功能。\n杜绝这类产品出现在干垃圾中。",
          "link": ["旧手机", "优盘"],
          "scene": ""
        }, {
          "name": "床品",
          "englishName": "chuangpin",
          "shareImgUrl": "http://i2.tiimg.com/693828/721521399450cf9e.jpg",
          "imgUrl": "../../images/recyclable/chuangpin.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布"],
          "solution": "棉被、枕头等床品均可回收，别随意丢弃。\n床垫属于大件物品，询问社区负责人该如何处理。\n当然，优先考虑转售他们。",
          "link": ["家纺"],
          "scene": ""
        }, {
          "name": "电线",
          "englishName": "dianxian",
          "shareImgUrl": "http://i2.tiimg.com/693828/505d9dfc68bfebec.jpg",
          "imgUrl": "../../images/recyclable/dianxian.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["电子", "塑料"],
          "solution": "要回收手机、笔记本电脑、键盘鼠标等这类小型电子产品请用「闲鱼」上门回收功能。\n禁止这类产品出现在干垃圾中。 ",
          "link": ["插座", "旧手机", "充电宝", "优盘"],
          "scene": ""
        }, {
          "name": "干净报纸",
          "englishName": "ganjinbaozhi",
          "shareImgUrl": "http://i2.tiimg.com/693828/406f9544ebfe50a3.jpg",
          "imgUrl": "../../images/recyclable/ganjingbaozhi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "报纸、试卷这类可书写的纸张都是可以回收的。\n除非沾满了油污，否则它们不应该出现在干垃圾中。\n鼓励将它们重复利用，比如吸油或作为包装纸。",
          "link": ["书本", "办公纸"],
          "scene": ""
        }, {
          "name": "锅具",
          "englishName": "guoju",
          "shareImgUrl": "http://i2.tiimg.com/693828/d06b7816f83fcf05.jpg",
          "imgUrl": "../../images/recyclable/guoju.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "锅具通常由不锈钢制成。尽量重复使用，当你确实不再需要它们时，请投入可回收物。\n陶土锅具不在此处理方式中，参考陶瓷餐具的处理方法。",
          "link": ["菜刀", "金属餐具", "陶瓷餐具"],
          "scene": ""
        }, {
          "name": "化妆品容器",
          "englishName": "huazhuangpinrongqi",
          "shareImgUrl": "http://i2.tiimg.com/693828/73f1197967500199.jpg",
          "imgUrl": "../../images/recyclable/hzprq.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料", "金属", "玻璃", "化学品"],
          "solution": "不要丢入有害垃圾桶！\n化妆品、护肤品、乳液等均为安全温和的生物化学品，因此它们的容器也是可回收物。\n回收前，请确保内部残余物已清空：液体可直接排入下水管。乳液类剂体用纸包裹后丢入干垃圾。",
          "link": ["口红管", "牙刷牙膏", "洗发水容器", "指甲油及容器"],
          "scene": ""
        }, {
          "name": "夹子",
          "englishName": "jiazi",
          "shareImgUrl": "http://i2.tiimg.com/693828/c10d59de472bfcf6.jpg",
          "imgUrl": "../../images/recyclable/jiazi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "不是干垃圾！有较高的利用价值。\n你可以将废弃的夹子夹食品袋以保存食物的新鲜，何必要丢掉它们。",
          "link": ["衣架", "回形针"],
          "scene": ""
        }, {
          "name": "家纺",
          "englishName": "jiafang",
          "shareImgUrl": "http://i2.tiimg.com/693828/7c63c3b15e45e033.jpg",
          "imgUrl": "../../images/recyclable/jiamang.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布"],
          "solution": "床单、被套、枕套等家纺类产品均可回收。\n羊毛地毯也可回收。\n闲置物品考虑转售。",
          "link": ["床品", "毛巾"],
          "scene": ""
        }, {
          "name": "剪刀",
          "englishName": "jiandao",
          "shareImgUrl": "http://i2.tiimg.com/693828/d66be9e957aff2bb.jpg",
          "imgUrl": "../../images/recyclable/jiandao.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "不是干垃圾。闲置物品请赠与或转售。",
          "link": ["美工刀及其刀片", "尺子", "五金工具及螺丝", "胶水", "胶带", "纸屑", "笔"],
          "scene": ""
        }, {
          "name": "酱料瓶",
          "englishName": "jiangliaopin",
          "shareImgUrl": "http://i2.tiimg.com/693828/2099ec83cc9342db.jpg",
          "imgUrl": "../../images/recyclable/jiangliaoping.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["玻璃", "食物"],
          "solution": "所有颜色的玻璃瓶子和罐子都可以放入你的回收物中。 回收前，你应该先冲洗。对于含有油性食物的瓶罐（如花生酱罐）应该将内容物先倒入湿垃圾再用纸巾擦拭，请不要将油脂倒入排水管中。\n请注意，它们的盖子也可以回收。",
          "link": ["啤酒瓶", "碎玻璃", "玻璃器皿", "食用油桶", "瓶盖", "动物油脂", "酱汁"],
          "scene": ""
        }, {
          "name": "金属餐具",
          "englishName": "jinshucanju",
          "shareImgUrl": "http://i2.tiimg.com/693828/71115ef06f60b6d1.jpg",
          "imgUrl": "../../images/recyclable/jinshucanju.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "金属餐具通常由不锈钢或黄铜制成，是非常有价值的物品。\n找不出你想要丢弃它们的理由，建议重复使用或转售。",
          "link": ["塑料餐具","玻璃器皿", "锅具", "木质餐具", "陶瓷餐具"],
          "scene": ""
        }, {
          "name": "金属盒子",
          "englishName": "jinshuhezi",
          "shareImgUrl": "http://i2.tiimg.com/693828/39105d13f1c8e0f9.jpg",
          "imgUrl": "../../images/recyclable/jinshuhezi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "通常用来装茶叶、糖果之类的干燥食品。\n材质通常为铝、铁，是非常有价值的可回收物。 千万不要当干垃圾丢了。回收前记得清空内部物体并保持干净。\n尽量重复利用。",
          "link": ["食品罐头", "干净塑料盒", "零食包装袋", "茶叶"],
          "scene": ""
        }, {
          "name": "旧包包",
          "englishName": "jiubaobao",
          "shareImgUrl": "http://i2.tiimg.com/693828/700bced84e5bf0b6.jpg",
          "imgUrl": "../../images/recyclable/jiubaobao.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布", "皮革"],
          "solution": "无伦什么材质的包均可回收。\n请考虑重复使用它们，哪怕用来买菜也不错。皮包请优先考虑捐赠或在二手平台转售，通常能卖到一个不错的价钱。",
          "link": ["旧衣服", "旧裤子", "旧帽子", "旧鞋"],
          "scene": ""
        }, {
          "name": "旧裤子",
          "englishName": "jiukuzi",
          "shareImgUrl": "http://i2.tiimg.com/693828/552e659cdbbd08c6.jpg",
          "imgUrl": "../../images/recyclable/jiukuzi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布"],
          "solution": "除内裤外，不穿的裤子都可以回收。\n优先考虑捐赠或在二手平台转售。",
          "link": ["内衣裤", "旧上衣", "旧帽子", "旧包", "旧鞋"],
          "scene": ""
        }, {
          "name": "旧帽子",
          "englishName": "jiumaozi",
          "shareImgUrl": "http://i2.tiimg.com/693828/cc9708cd16a3fdc8.jpg",
          "imgUrl": "../../images/recyclable/jiumaozi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布"],
          "solution": "不戴的帽子可以回收。\n优先考虑捐赠或在二手平台转售。",
          "link": ["旧裤子", "旧上衣", "旧包", "旧鞋"],
          "scene": ""
        }, {
          "name": "旧手机",
          "englishName": "jiushouji",
          "shareImgUrl": "http://i2.tiimg.com/693828/13ec630e508cd7ec.jpg",
          "imgUrl": "../../images/recyclable/jiushouji.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["电子", "金属"],
          "solution": "要回收手机、笔记本电脑、键盘鼠标等这类小型电子产品请用「闲鱼」上门回收功能。\n禁止这类产品出现在干垃圾中。\n如果有电池的话，先将电池取出按电池规则处理。",
          "link": ["纽扣电池", "纽扣电池", "碱性电池", "手机电池", "充电宝", "优盘", "电线"],
          "scene": ""
        }, {
          "name": "旧鞋子",
          "englishName": "jiuxiezi",
          "shareImgUrl": "http://i2.tiimg.com/693828/fce920fef10a33b8.jpg",
          "imgUrl": "../../images/recyclable/jiuxiezi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布", "皮革", "橡胶"],
          "solution": "无伦什么材质的鞋子均可回收。\n皮鞋请优先考虑转售它们，它们通常在二手平台能卖到一个不错的价钱。",
          "link": ["旧衣服", "旧裤子", "旧帽子", "旧包"],
          "scene": ""
        }, {
          "name": "旧衣服",
          "englishName": "jiuyifu",
          "shareImgUrl": "http://i2.tiimg.com/693828/42ee1a9e555930ad.jpg",
          "imgUrl": "../../images/recyclable/jiuyifu.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["棉布"],
          "solution": "不穿的上衣可以回收。\nT恤类的上衣可以考虑作为抹布再利用。此外，优先考虑捐赠或在二手平台转售。",
          "link": ["旧裤子","旧帽子","旧包", "旧鞋"],
          "scene": ""
        }, {
          "name": "卷筒纸芯",
          "englishName": "juantongzhixin",
          "shareImgUrl": "http://i2.tiimg.com/693828/e8089479dd8c7e11.jpg",
          "imgUrl": "../../images/recyclable/juantongzhixin.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "卷筒卫生纸是干垃圾，而其纸芯是可回收的。\n你可以用它们来包装糖果、首饰之类的小礼物。",
          "link": ["卫生纸"],
          "scene": ""
        }, {
          "name": "卡",
          "englishName": "ka",
          "shareImgUrl": "http://i2.tiimg.com/693828/dd68258b5291619b.jpg",
          "imgUrl": "../../images/recyclable/ka.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "不用的交通卡、充值卡、购物卡不要丢，它们是可以被回收的。\n闲鱼」平台有上门回收功能。",
          "link": [""],
          "scene": ""
        }, {
          "name": "快递瓦楞纸板箱",
          "englishName": "kuaidiwalengzhiban",
          "shareImgUrl": "http://i2.tiimg.com/693828/3d70c9aa99e7ab28.jpg",
          "imgUrl": "../../images/recyclable/wlzx.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "展平并放入可回收物或放在垃圾桶的旁边。确保干燥清洁！\n请注意，在拆完快递后，请先顺手撕掉纸箱上的胶带，将胶带投入干垃圾，因为胶带上的胶会黏住加工的机器。当然，重复利用是最好的，你可以将某一个纸板箱用来存储平时家庭生产出来的可回收物。同时，零星的硬纸板也是可回收的。",
          "link": ["泡沫塑料", "防碎气泡膜", "快递塑料袋", "快递信封纸袋", "胶带"],
          "scene": ""
        }, {
          "name": "快递信封纸袋",
          "englishName": "kuaidixinfen",
          "shareImgUrl": "http://i2.tiimg.com/693828/657d8a52abc40503.jpg",
          "imgUrl": "../../images/recyclable/xfzd.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "不同于快递塑料袋、包裹文件的快递信封纸袋是可回收物。不要丢入干垃圾中，减少浪费并尝试重复利用。\n回收前先将涉及隐私信息涂抹，如果信封带有塑料窗，需将其移除。",
          "link": ["快递塑料袋"],
          "scene": ""
        }, {
          "name": "利乐纸盒",
          "englishName": "lilezhihe",
          "shareImgUrl": "http://i2.tiimg.com/693828/81d4d261d3c682c1.jpg",
          "imgUrl": "../../images/recyclable/lilezhihe.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "类似牛奶盒、盒型的果汁容器、纸质冰淇淋桶等尽量剪开并清洗干净，是可以投入可回收物的。",
          "link": ["奶茶外带杯", "饮料塑料瓶", "酸奶罐", "纸质包装盒", "啤酒饮料瓶", "饮料易拉罐"],
          "scene": ""
        }, {
          "name": "美工刀及其刀片",
          "englishName": "meigongdaojid",
          "shareImgUrl": "http://i2.tiimg.com/693828/1d343e5196707e94.jpg",
          "imgUrl": "../../images/recyclable/mgddp.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "不是干垃圾。哪怕是替换的刀片也是可回收物！\n闲置物品请赠与或转售。 ",
          "link": ["剪刀", "尺子", "五金工具及螺丝", "胶水", "胶带", "纸屑", "菜刀", "笔"],
          "scene": ""
        }, {
          "name": "木质餐具",
          "englishName": "muzhicanju",
          "shareImgUrl": "http://i2.tiimg.com/693828/5dac9b8f9cbd8473.jpg",
          "imgUrl": "../../images/recyclable/muzhicanju.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["木"],
          "solution": "不是干垃圾！\n木资源是非常珍贵的。所以木筷子、木碗等餐具均可以回收。\n优先考虑将木碗重新利用，比如作为花盆",
          "link": ["塑料餐具", "玻璃器皿", "金属餐具", "陶瓷餐具"],
          "scene": ""
        }, {
          "name": "泡沫塑料",
          "englishName": "paomosuliao",
          "shareImgUrl": "http://i2.tiimg.com/693828/8809855940ac7030.jpg",
          "imgUrl": "../../images/recyclable/paomosuliao.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "用于快递防震的干净泡沫塑料，可用于回收。\n但被食物污染过的泡沫塑料餐盒请丢入干垃圾桶。",
          "link": ["防碎气泡膜", "快递塑料袋", "快递瓦楞纸板箱", "快递信封纸袋", "胶带"],
          "scene": ""
        }, {
          "name": "啤酒瓶",
          "englishName": "pijiupin",
          "shareImgUrl": "http://i2.tiimg.com/693828/407b5a897d4793ff.jpg",
          "imgUrl": "../../images/recyclable/pijiuping.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["玻璃"],
          "solution": "所有颜色的玻璃瓶子和罐子都可以放入你的回收物中。但是在回收前，你应该先清空内部物体并冲洗干净。\n请注意，它们的盖子也可以回收。\n总结，不要把它们当干垃圾丢了！",
          "link": ["饮料塑料瓶", "食用油桶", "碎玻璃", "玻璃器皿", "酱料瓶", "饮料易拉罐", "瓶盖"],
          "scene": ""
        }, {
          "name": "瓶盖",
          "englishName": "pinggai",
          "shareImgUrl": "http://i2.tiimg.com/693828/b0e22ffc759d1a78.jpg",
          "imgUrl": "../../images/recyclable/pinggai.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "所有塑料制或金属制的盖子都是可回收的。 最好将它们盖紧或塞入原始容器中一并回收。\n咖啡杯盖，脆性饮料杯盖应作为干垃圾处理。",
          "link": ["啤酒瓶", "酱料瓶", "塑料饮料瓶", "奶茶外带杯"],
          "scene": ""
        }, {
          "name": "食品罐头",
          "englishName": "shipinguantou",
          "shareImgUrl": "http://i2.tiimg.com/693828/752b754e02695e39.jpg",
          "imgUrl": "../../images/recyclable/shipingguantou.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "食物"],
          "solution": "冲洗并回收食物罐头如沙丁鱼罐头、菠萝罐头，并且无需撕掉标签。\n除非罐头里装的是危险物质，否则它们不该出现在干垃圾中。",
          "link": ["干净塑料盒", "零食包装袋", "金属盒", "油漆桶", "动物油脂", "酱汁", "动物肉类", "水果及其果皮"],
          "scene": ""
        }, {
          "name": "食用油桶",
          "englishName": "shiyongyoutong",
          "shareImgUrl": "http://i2.tiimg.com/693828/71dc131a55f55482.jpg",
          "imgUrl": "../../images/recyclable/shiyongyoutong.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "空油桶虽然沾满了油，但这并非是食物残渣的污染，所以请将内部残油清空并清洗干净后丢入可回收垃圾桶，当然最好的处理方式是重复利用。\n如有大量的食用油需要处理，请参考动物油脂的处理方法。",
          "link": ["饮料塑料瓶", "酱料瓶"],
          "scene": ""
        }, {
          "name": "书本",
          "englishName": "shuben",
          "shareImgUrl": "http://i2.tiimg.com/693828/23f89a66ba85ef61.jpg",
          "imgUrl": "../../images/recyclable/shuben.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "尽量捐赠旧书或转售，可预约「闲鱼」上门回收服务。实在不行，再投入可回收物。\n杂志、宣传册同书本处理方式。",
          "link": ["干净报纸", "办公纸"],
          "scene": ""
        }, {
          "name": "梳子",
          "englishName": "shuzi",
          "shareImgUrl": "http://i2.tiimg.com/693828/eb876452060078d5.jpg",
          "imgUrl": "../../images/recyclable/shuzi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["木", "塑料"],
          "solution": "塑料制和木制的梳子官方定义为可回收。",
          "link": ["化妆刷"],
          "scene": ""
        }, {
          "name": "塑料餐具",
          "englishName": "suliaocanju",
          "shareImgUrl": "http://i2.tiimg.com/693828/b5b94905e91602e4.jpg",
          "imgUrl": "../../images/recyclable/suliaocanju.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "塑料碗、碟、杯等均是为可重复使用而设计的。虽然在上海这些塑料品都可回收，但它们通常由专有的塑料化合物制成。如果可以的话，请重新使用它们、捐赠或转售。",
          "link": ["一次性餐具", "纸杯", "玻璃器皿", "金属餐具", "锅具", "木质餐具", "陶瓷餐具"],
          "scene": ""
        }, {
          "name": "酸奶罐",
          "englishName": "suannaiguan",
          "shareImgUrl": "http://i2.tiimg.com/693828/4ae0d2f48b0b366e.jpg",
          "imgUrl": "../../images/recyclable/suannaiguan.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "酸奶罐这样的硬塑料容器当然也是可回收的。",
          "link": ["饮料塑料瓶", "利乐纸盒"],
          "scene": ""
        }, {
          "name": "碎玻璃",
          "englishName": "suiboli",
          "shareImgUrl": "http://i2.tiimg.com/693828/3eaf974e6213cc7b.jpg",
          "imgUrl": "../../images/recyclable/suiboli.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["玻璃"],
          "solution": "上海官方规定，碎玻璃可以回收。但请先用布料或纸板箱包裹后投放。",
          "link": ["啤酒瓶", "玻璃器皿"],
          "scene": ""
        }, {
          "name": "玩具",
          "englishName": "wanju",
          "shareImgUrl": "http://i2.tiimg.com/693828/d790e081d998ee8b.jpg",
          "imgUrl": "../../images/recyclable/wanju.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料", "木", "棉布"],
          "solution": "最好的方式是将闲置的玩具修理或转售。",
          "link": ["羽毛球及球拍", "足球"],
          "scene": ""
        }, {
          "name": "五金工具及螺丝钉",
          "englishName": "wujingongju",
          "shareImgUrl": "http://i2.tiimg.com/693828/b17fd85a983f59e4.jpg",
          "imgUrl": "../../images/recyclable/wjjls.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属", "塑料"],
          "solution": "螺丝刀、扳手、榔头都可回收。哪怕是替换下来的螺丝钉也是可回收物！请重复使用它们。\n回形针和订书钉是干垃圾。",
          "link": ["回形针", "美工刀及其刀片", "剪刀", "尺子"],
          "scene": ""
        }, {
          "name": "洗洁精容器",
          "englishName": "xijiejingrongqi",
          "shareImgUrl": "http://i2.tiimg.com/693828/e40647c6e275b41e.jpg",
          "imgUrl": "../../images/recyclable/xjjrq.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "你可以回收大多数塑料瓶、壶和盒子。\n装有洗发水、沐浴露和洗衣粉、洗衣液等漂白剂物质的容器都可以回收，必须先将他们彻底冲洗干净。\n然而，不可回收装有指甲油、消毒水等有害物质的容器。这些都是有害垃圾。",
          "link": ["洗衣液容器", "消毒剂容器"],
          "scene": ""
        }, {
          "name": "洗衣液容器",
          "englishName": "xiyiyerongqi",
          "shareImgUrl": "http://i2.tiimg.com/693828/31622d2d59ac1715.jpg",
          "imgUrl": "../../images/recyclable/xyyrq.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "你可以回收大多数塑料瓶、壶和盒子。\n装有洗发水、沐浴露和洗衣粉、洗衣液等漂白剂物质的容器都可以回收，必须先将他们彻底冲洗干净。\n然而，不可回收装有指甲油、消毒水等有害物质的容器。这些都是有害垃圾。",
          "link": ["洗发水容器", "消毒水容器", "洗洁精容器"],
          "scene": ""
        }, {
          "name": "洗浴品容器",
          "englishName": "xiyupinrongqi",
          "shareImgUrl": "http://i2.tiimg.com/693828/83110e123b7ad717.jpg",
          "imgUrl": "../../images/recyclable/xyprq.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "你可以回收大多数塑料瓶、壶和盒子。\n装有洗发水、沐浴露和洗衣粉、洗衣液等漂白剂物质的容器都可以回收，必须先将他们彻底冲洗干净。\n然而，不可回收装有指甲油、消毒水等有害物质的容器。这些都是有害垃圾。",
          "link": ["化妆品容器", "牙刷牙膏", "洗衣粉液瓶", "消毒水容器", "洗洁精容器", "指甲油及容器"],
          "scene": ""
        }, {
          "name": "衣架",
          "englishName": "yijia",
          "shareImgUrl": "http://i2.tiimg.com/693828/73924bebb59ebd9e.jpg",
          "imgUrl": "../../images/recyclable/yijia.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料", "金属", "木"],
          "solution": "无论是什么材质的衣架都被官方认为是可回收物品。\n更好的建议是将他们转售或重复利用，细塑料衣架可被拉直用做悬挂绳挂家庭照片或灯泡等。",
          "link": ["夹子"],
          "scene": ""
        }, {
          "name": "银饰",
          "englishName": "yinshi",
          "shareImgUrl": "http://i2.tiimg.com/693828/cd6934f9e80776ec.jpg",
          "imgUrl": "../../images/recyclable/yinshi.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "耳环、项链、戒指等饰品都是非常有价值的物品。\n想不出你丢弃它们的理由。请收藏、赠与或转售。",
          "link": ["旧鞋子", "旧帽子", "旧包包"],
          "scene": ""
        }, {
          "name": "饮料塑料瓶",
          "englishName": "yinliaosuliao",
          "shareImgUrl": "http://i2.tiimg.com/693828/a3eb6ac9c6aa2cd2.jpg",
          "imgUrl": "../../images/recyclable/ylslp.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "不要丢入干垃圾桶！任何情况下，你都可以回收所有塑料食品容器：瓶子、牛奶桶、食用油桶等。请清空内部液体并尽量冲洗干净。\n如果可能，请重复利用它们。",
          "link": ["食用油桶", "酸奶罐", "利乐纸盒", "啤酒饮料瓶", "饮料易拉罐"],
          "scene": ""
        }, {
          "name": "饮料易拉罐",
          "englishName": "yinliaoyila",
          "shareImgUrl": "http://i2.tiimg.com/693828/93026fd5ae2b374b.jpg",
          "imgUrl": "../../images/recyclable/ylylg.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "非常常见的可回收物，使用再生铝制造的东西比使用新材料节省98％的能量！\n千万不要当干垃圾丢了。回收前记得清空内部液体并清洗干净。",
          "link": ["奶茶外带杯", "饮料塑料瓶", "酸奶罐", "利乐纸盒", "啤酒瓶"],
          "scene": ""
        }, {
          "name": "硬塑料盒",
          "englishName": "yingsuliaohe",
          "shareImgUrl": "http://i2.tiimg.com/693828/4f83bc0503924046.jpg",
          "imgUrl": "../../images/recyclable/yslh.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["塑料"],
          "solution": "铁汁记住一句话，所有的硬塑料盒都可回收，所有的软塑料盒都是垃圾。\n塑料花盆、塑料桶、塑料盆同此处理方法。请尽量重复使用或转赠。",
          "link": ["软塑料盒","塑料餐具", "金属盒"],
          "scene": ""
        }, {
          "name": "优盘",
          "englishName": "youpan",
          "shareImgUrl": "http://i2.tiimg.com/693828/c33aac8deda5f112.jpg",
          "imgUrl": "../../images/recyclable/youpan.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["电子", "塑料", "金属"],
          "solution": "要回收手机、笔记本电脑、键盘鼠标等这类小型电子产品请用「闲鱼」上门回收功能。\n杜绝这类产品出现在干垃圾中。",
          "link": ["旧手机", "充电宝"],
          "scene": ""
        }, {
          "name": "砧板",
          "englishName": "zhanban",
          "shareImgUrl": "http://i2.tiimg.com/693828/5325c1fc00290a01.jpg",
          "imgUrl": "../../images/recyclable/zhanban.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["木", "塑料"],
          "solution": "塑料制和木制的砧板皆可回收，不要放入干垃圾了。",
          "link": ["菜刀"],
          "scene": ""
        }, {
          "name": "纸包装盒",
          "englishName": "zhibaozhuanghe",
          "shareImgUrl": "http://i2.tiimg.com/693828/e69bddb28a3dc012.jpg",
          "imgUrl": "http://i1.fuimg.com/693828/291a719271f293ce.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "",
          "link": ["硬塑料盒", "软塑料盒", "金属盒", "零食包装袋", "药品及其包装", "咳嗽药水及其包装"],
          "scene": ""
        }, {
          "name": "纸袋",
          "englishName": "zhidai",
          "shareImgUrl": "http://i2.tiimg.com/693828/e3b3be9b7d954ca2.jpg",
          "imgUrl": "../../images/recyclable/zhidai.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["纸"],
          "solution": "清洁而干燥的纸袋可以回收。\n请帮助减少浪费：重复使用或携带帆布袋购物。",
          "link": ["塑料袋"],
          "scene": ""
        }, {
          "name": "指甲钳",
          "englishName": "zhijiaqian",
          "shareImgUrl": "http://i2.tiimg.com/693828/1ee049e7fe4ca513.jpg",
          "imgUrl": "../../images/recyclable/zhijiaqian.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["金属"],
          "solution": "不要投入干垃圾。请重复利用、捐赠或转售。",
          "link": ["指甲皮屑", "剪刀"],
          "scene": ""
        }, {
          "name": "足球",
          "englishName": "zuqiu",
          "shareImgUrl": "http://i2.tiimg.com/693828/13feb9d80f413713.jpg",
          "imgUrl": "../../images/recyclable/zuqiu.jpg",
          "copyright": "",
          "type": "可回收物",
          "material": ["橡胶"],
          "solution": "足球、篮球等橡胶类运动物品都是可回收物。\n羽毛球及球拍不可回收。",
          "link": ["羽毛球及球拍", "玩具"],
          "scene": ""
        }
      ]
    }]
}